# Site settings
baseurl:  # the subpath of your site, e.g. /blog/
url:      # the base hostname & protocol for your site
title:       Riccardo Scandariato
description: All about my photo adventures...

# Build settings
markdown: kramdown

excerpt_separator: "<!--break-->"

# Custom variables
galleries_path: "/assets/galleries"
blogpics_path:  "/blogpics"

collections:
  galleries:
    output: true

# Pagination
paginate:      5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
