# Site settings
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
title: Riccardo Scandariato
description: All about my photo adventures...

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate-v2
